name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        bun-version: [latest, canary]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Bun ${{ matrix.bun-version }}
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ matrix.bun-version }}

    - name: Install dependencies
      run: bun install --frozen-lockfile

    - name: Run linter
      run: bun run lint

    - name: Run type check
      run: bun run type-check

    - name: Run tests
      run: bun run test:ci

    - name: Build package
      run: bun run build

    - name: Upload coverage
      if: matrix.bun-version == 'latest'
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage/coverage-final.json
        fail_ci_if_error: false
